
version: 2
jobs:
  build_prod:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build for web
          command: npm run build --prod
      - persist_to_workspace:
          root: .
          paths:
           - www/*
  deploy_prod:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: www
      - run:
          name: install aws cli
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: deploy
          command: aws s3 sync www/* s3://techd.jp --delete --region ap-northeast-1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_prod:
          filters:
            branches:
              only: master
      - deploy_prod:
          requires:
            - build_prod
          filters:
            branches:
              only: master
